### ISSUE TITLE
namespace is missing in queue name construction

### ISSUE THREAD

**Issue by shdunning** [carstencodes/pykiq#3]
For our sidekiq deployment we use a namespace that prefixes the queue name; for example `sidekiq:queue:default`. However the way queues are constructed in `pykiq` it doesn't allow for an optional namespace to be present. This template would need to be modified:

https://github.com/carstencodes/pykiq/blob/10dcc7c5ee53a7fb97572264ae8804c22fa6eb78/src/pykiq/protocol.py#L32

**Comment by carstencodes** [comment]
I'll look what I can do. I'll try to add it within the next days.

**Comment by carstencodes** [comment]
Ok, I consider this as an edge case.

@shdunning I have a proposal in #4 running.

The basic idea is adding namespaces when constructing the sidekiq queue instance.

For details you can refer to the `_EmptySidekiqNamespace` class in the sidekiq.py implementation.

I will drop support for Python 3.7 in the next version, since for the tests coming in v0.11, I'm using protocol classes which are introduced in Python 3.8.

**Comment by carstencodes** [comment]
As there was no objection by @shdunning I'm closing the issue as it was released with v0.10.3
